	Python3 anaconda is now loaded in your environment. 
	For all commands you should now do the following: 
	source $condaDotFile

	GCC 9.1.0 environment now loaded

	CUDA-11.0 loaded

	Swig-4.0.2 loaded

	OpenMPI 4.0.5, built with GCC, UCX and CUDA, is now loaded in your
environment. 
	Documentation can be found online at http://www.open-mpi.org/doc/

	Nano-5.3 loaded

-------------------------------------------------------------------------------
There are messages associated with the following module(s):
-------------------------------------------------------------------------------

use.dev:
   Meta-module to load development software, e.g. various compiler versions.
-------------------------------------------------------------------------------

/jmain02/home/J2AD005/jck01/fxs62-jck01/repos/microcircuit_network/mc/data/randman/dataset.py:6: NumbaDeprecationWarning: [1mThe 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.[0m
  def f(x, th_a, th_b, th_c, alpha, m, d, n_c):
make: Entering directory `/jmain02/home/J2AD005/jck01/fxs62-jck01/repos/microcircuit_network/mc/network_job_3_CODE'
make: Nothing to be done for `all'.
make: Leaving directory `/jmain02/home/J2AD005/jck01/fxs62-jck01/repos/microcircuit_network/mc/network_job_3_CODE'
swig/python detected a memory leak of type 'CodeGenerator::CUDA::Backend *', no destructor found.
Traceback (most recent call last):
  File "/jmain02/home/J2AD005/jck01/fxs62-jck01/.conda/envs/test/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/jmain02/home/J2AD005/jck01/fxs62-jck01/.conda/envs/test/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/jmain02/home/J2AD005/jck01/fxs62-jck01/repos/microcircuit_network/mc/experiments/randman/run_rate.py", line 165, in <module>
    epoch_ax, acc, loss, rec_neur, rec_syn, run_time = train_and_test_network(_tmp_params,
  File "/jmain02/home/J2AD005/jck01/fxs62-jck01/repos/microcircuit_network/mc/experiments/utils.py", line 173, in train_and_test_network
    net = Network(NETWORK_NAME, network_model,
  File "<string>", line 19, in __init__
  File "/jmain02/home/J2AD005/jck01/fxs62-jck01/repos/microcircuit_network/mc/mc/network.py", line 378, in __post_init__
    self.genn_model.load(num_recording_timesteps=self.spike_buffer_size)
  File "/jmain02/home/J2AD005/jck01/fxs62-jck01/repos/genn/pygenn/genn_model.py", line 640, in load
    self._slm.allocate_mem()
  File "/jmain02/home/J2AD005/jck01/fxs62-jck01/repos/genn/pygenn/genn_wrapper/SharedLibraryModelNumpy.py", line 133, in allocate_mem
    return _SharedLibraryModelNumpy.SharedLibraryModel_f_allocate_mem(self)
RuntimeError: runner.cc: 2387: cuda error 101: invalid device ordinal
